# Generated by Django 5.2.7 on 2025-11-05 06:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Joylashuv',
                'verbose_name_plural': 'Joylashuvlar',
                'indexes': [models.Index(fields=['lat', 'lng'], name='journey_loc_lat_092aeb_idx'), models.Index(fields=['is_available'], name='journey_loc_is_avai_f2c0b6_idx')],
                'unique_together': {('lat', 'lng')},
            },
        ),
        migrations.CreateModel(
            name='UserLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.BigIntegerField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('live_period', models.IntegerField(blank=True, null=True)),
                ('heading', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(360)])),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_locations', to='journey.location')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi joylashuvi',
                'verbose_name_plural': 'Foydalanuvchi joylashuvlari',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='journey_use_user_d9e891_idx')],
            },
        ),
    ]
