# Generated by Django 5.2.7 on 2025-11-05 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userlocation',
            unique_together={('location',)},
        ),
    ]
