# Generated by Django 5.2.7 on 2025-11-05 15:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0002_alter_userlocation_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Mashina nomi')),
                ('model', models.CharField(max_length=100, verbose_name='Model')),
                ('car_type', models.CharField(choices=[('economy', 'Economy'), ('standard', 'Standard'), ('business', 'Business')], default='standard', max_length=20, verbose_name='Mashina turi')),
                ('color', models.CharField(blank=True, max_length=50, verbose_name='Rangi')),
                ('year', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1990), django.core.validators.MaxValueValidator(2030)], verbose_name='Ishlab chiqarilgan yili')),
                ('license_plate', models.CharField(max_length=20, unique=True, verbose_name='Davlat raqami')),
                ('capacity', models.PositiveIntegerField(default=4, verbose_name='Oʻrindiqlar soni')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mashina',
                'verbose_name_plural': 'Mashinalar',
                'indexes': [models.Index(fields=['license_plate'], name='journey_car_license_35b7b0_idx'), models.Index(fields=['is_active'], name='journey_car_is_acti_5f423a_idx')],
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(db_index=True, unique=True, verbose_name='Telegram ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ism')),
                ('contact', models.CharField(db_index=True, max_length=20, verbose_name='Telefon raqam')),
                ('status', models.CharField(choices=[('active', 'Faol'), ('inactive', 'Faol emas'), ('busy', 'Band'), ('offline', 'Offline')], default='inactive', max_length=20, verbose_name='Holati')),
                ('rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Reyting')),
                ('total_trips', models.PositiveIntegerField(default=0, verbose_name='Jami sayohatlar')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Tasdiqlangan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drivers', to='journey.car', verbose_name='Mashina')),
                ('current_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drivers_current', to='journey.location', verbose_name='Joriy joylashuv')),
            ],
            options={
                'verbose_name': 'Haydovchi',
                'verbose_name_plural': 'Haydovchilar',
            },
        ),
        migrations.CreateModel(
            name='DriverRoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='road_current', to='journey.location', verbose_name='Joriy joylashuv')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roads', to='journey.driver', verbose_name='Haydovchi')),
                ('from_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='road_starts', to='journey.location', verbose_name='Boshlanish joyi')),
                ('to_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='road_ends', to='journey.location', verbose_name='Tugash joyi')),
            ],
            options={
                'verbose_name': 'Haydovchi yoʻli',
                'verbose_name_plural': 'Haydovchi yoʻllari',
            },
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(db_index=True, unique=True, verbose_name='Telegram ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ism')),
                ('contact', models.CharField(max_length=20, unique=True, verbose_name='Telefon raqam')),
                ('rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=3, verbose_name='Reyting')),
                ('total_trips', models.PositiveIntegerField(default=0, verbose_name='Jami sayohatlar')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Yoʻlovchi',
                'verbose_name_plural': 'Yoʻlovchilar',
                'indexes': [models.Index(fields=['telegram_id'], name='journey_pas_telegra_50f58d_idx'), models.Index(fields=['is_active'], name='journey_pas_is_acti_58c941_idx')],
            },
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('creator', models.BigIntegerField(db_index=True, verbose_name='Yaratuvchi Telegram ID')),
                ('expected_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Kutilayotgan narx')),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Yakuniy narx')),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Masofa (km)')),
                ('estimated_duration_min', models.PositiveIntegerField(blank=True, null=True, verbose_name='Taxminiy davomiylik (min)')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Boshlangan vaqt')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Tugagan vaqt')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='travels', to='journey.driver', verbose_name='Haydovchi')),
                ('from_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='travels_from', to='journey.location', verbose_name='Boshlanish joyi')),
                ('to_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='travels_to', to='journey.location', verbose_name='Tugash joyi')),
            ],
            options={
                'verbose_name': 'Sayohat',
                'verbose_name_plural': 'Sayohatlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TravelInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_female', models.BooleanField(default=False, verbose_name='Ayol yoʻlovchi bor')),
                ('status', models.CharField(choices=[('created', 'Yaratildi'), ('searching_driver', 'Haydovchi qidirilmoqda'), ('driver_found', 'Haydovchi topildi'), ('driver_accepted', 'Haydovchi qabul qildi'), ('on_the_way', 'Yoʻlda'), ('arrived', 'Yetib keldi'), ('started', 'Sayohat boshlandi'), ('completed', 'Yakunlandi'), ('cancelled', 'Bekor qilindi'), ('failed', 'Xatolik')], default='created', max_length=20, verbose_name='Holati')),
                ('special_requests', models.TextField(blank=True, verbose_name='Maxsus soʻrovlar')),
                ('driver_rating', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(5)], verbose_name='Haydovchi reytingi')),
                ('passenger_rating', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(5)], verbose_name='Yoʻlovchi reytingi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('passengers', models.ManyToManyField(blank=True, related_name='travels', to='journey.passenger', verbose_name='Yoʻlovchilar')),
                ('travel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='journey.travel', verbose_name='Sayohat')),
            ],
            options={
                'verbose_name': "Sayohat ma'lumoti",
                'verbose_name_plural': "Sayohat ma'lumotlari",
            },
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['telegram_id'], name='journey_dri_telegra_3261b4_idx'),
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['status'], name='journey_dri_status_f62bd5_idx'),
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['rating'], name='journey_dri_rating_2eacb9_idx'),
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['is_verified'], name='journey_dri_is_veri_eff037_idx'),
        ),
        migrations.AddIndex(
            model_name='driverroad',
            index=models.Index(fields=['driver', 'is_active'], name='journey_dri_driver__a7db03_idx'),
        ),
        migrations.AddIndex(
            model_name='driverroad',
            index=models.Index(fields=['from_location', 'to_location'], name='journey_dri_from_lo_de23af_idx'),
        ),
        migrations.AddIndex(
            model_name='travel',
            index=models.Index(fields=['creator', 'created_at'], name='journey_tra_creator_9610a9_idx'),
        ),
        migrations.AddIndex(
            model_name='travel',
            index=models.Index(fields=['driver', 'created_at'], name='journey_tra_driver__c68dcb_idx'),
        ),
    ]
